name: 'Add Label'
description: 'Add a label when someone raise a PR with a given base branch'
inputs:
  labels:
    description: "Labels to add"
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
