name: Add Label
on:
  pull_request:
    branches:
      - feat/label-4
      - feat/label-5
      - main
    types:
      - opened

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          labels: |
            { feat/label-4: 'label-4, new',
              feat/label-5: 'label-5'
            }
          default: |
            bug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
